version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: ticket-mysql
    restart: always
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      TZ: Asia/Seoul
    command:
      - --server-id=1
      - --log-bin=mysql-bin
      - --binlog-format=ROW
      - --binlog-row-image=FULL
      - --gtid-mode=ON
      - --enforce-gtid-consistency=ON
      - --innodb_flush_log_at_trx_commit=2
      - --sync_binlog=0
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - ticketon-network

  reservation-redis:
    image: redis:7.0.11
    container_name: reservation-redis
    restart: always
    ports:
      - "6380:6380"
    command: [ "redis-server", "--port", "6380", "--appendonly", "yes" ] # AOF 활성화
    volumes:
      - redis-data:/data
    networks:
      - ticketon-network

  kafka:
    image: bitnami/kafka:4.0
    container_name: kafka
    restart: always
    ports:
      - "9092:9092"
    environment:
      # KRAFT 설정
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_PROCESS_ROLES: controller,broker
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      # 내부 통신용 Listener
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      # 기타 설정
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_CFG_LOG_RETENTION_MS: 600000
    volumes:
      - kafka-data:/bitnami/kafka
    networks:
      - ticketon-network

  kafka-connect:
    image: debezium/connect:2.6
    container_name: kafka-connect
    restart: always
    ports:
      - "8083:8083"
    environment:
      BOOTSTRAP_SERVERS: "kafka:9092"
      GROUP_ID: "connect-cluster"
      CONFIG_STORAGE_TOPIC: "connect_configs"
      OFFSET_STORAGE_TOPIC: "connect_offsets"
      STATUS_STORAGE_TOPIC: "connect_status"
      CONFIG_STORAGE_REPLICATION_FACTOR: "1"
      OFFSET_STORAGE_REPLICATION_FACTOR: "1"
      STATUS_STORAGE_REPLICATION_FACTOR: "1"
      KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_PLUGIN_PATH: "/kafka/connect"
    depends_on:
      - kafka
      - mysql
    networks:
      - ticketon-network


  api-server-1:
    image: brianchoi506/ticket-api-server:latest
    container_name: api-server-1
    restart: always
    ports:
      - "8081:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      TZ: Asia/Seoul
      LOGGING_FILE_NAME: /var/log/ticketon/application.log
    env_file:
      - .env
    volumes:
      - ./logs:/var/log/ticketon # 호스트에 로그 파일 저장
    depends_on:
      - mysql
      - kafka
      - reservation-redis
    networks:
      - ticketon-network

  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    restart: always
    command: [
      "run",
      "--server.http.listen-addr=0.0.0.0:12345",
      "--storage.path=/var/lib/alloy/data",
      "/etc/alloy/config.alloy"
    ]
    volumes:
      - ./monitoring/alloy/config.alloy:/etc/alloy/config.alloy
      - ./logs:/var/log/ticketon:ro # API 서버 로그 읽기용
      - alloy-data:/var/lib/alloy/data
    ports:
      - "12345:12345"
    networks:
      - ticketon-network

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: always
    ports:
      - "9090:9090"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.enable-remote-write-receiver"
      - "--storage.tsdb.retention.time=15d"
    volumes:
      - prometheus-data:/prometheus
    networks:
      - ticketon-network

  loki:
    image: grafana/loki:latest
    container_name: loki
    restart: always
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/loki-config.yml
    volumes:
      - ./monitoring/loki/loki-config.yml:/etc/loki/loki-config.yml
      - loki-data:/loki
    networks:
      - ticketon-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus
      - loki
    networks:
      - ticketon-network

networks:
  ticketon-network:
    driver: bridge

volumes:
  mysql-data:
  redis-data:
  kafka-data:
  prometheus-data:
  loki-data:
  grafana-data:
  alloy-data: