spring:
  profiles:
    active: docker
  config:
    import: "optional:file:.env[.properties]"

  jpa:
    hibernate:
      ddl-auto: create-drop
      database-platform: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: false
        format_sql: false


logging:
  level:
    root: INFO
    io.opentelemetry: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
    org.springframework.orm.jpa: DEBUG
    org.springframework.transaction: debug

#snail-catch:
#  enabled: false
#  repository-pointcut: execution(* com.ticketon.ticketon.domain..repository..*(..))
#  api-key: 13a4d744b37046e2b62f90077c0936f8



toss:
  secret-key: ${TOSS_SECRET_KEY}
  client-key: ${TOSS_CLIENT_KEY}
  base-url: https://api.tosspayments.com/v1/payments
  confirm-end-point: /confirm
  cancel-end-point: /cancel